site: The Maker Effect Foundation

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap

#begin seo
title: The Maker Effect Foundation
tagline: Make With Us!
description: The Maker Effect is the sum of the personal growth, professional success, community development, and continuous innovation that results when makers learn, educate, share, and create together.
logo: /images/site-branding/square_black.png

url:
baseurl:

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

sass:
  style: compressed

plugins:
  - jekyll-sitemap

paginate: 7
paginate_path: "/blog/page-:num/"
